### ISSUE TITLE
stringify: optional argument for FeatureCollection properties

### ISSUE THREAD

**Issue by anandthakker** [node-geojson/geojson-stream#1]
@tmcw Would you accept a PR to take an optional parameter to stringify for the resulting featurecollection's properties?

**Comment by tmcw** [comment]
Not super inclined: the GeoJSON FeatureCollection object is not specified to have a "properties" property, and I haven't seen any code that would actually handle or parse it if it did have one. The only properties expected from a FeatureCollection are:
- features (required)
- crs (optional)
- bbox (optional)

**Comment by anandthakker** [comment]
Oh dear, I didn't realize that.  My mistake, sorry!
